blank_issues_enabled: true
contact_links:
  - name: Composers Desktop Project
    url: https://www.composersdesktop.com
    about: The audio processing project CDP Web is based on. Not affiliated with CDP Ltd.
