// Build ./manual.json — the browsable manual shown from Help ▸ Manual.
//
// Source: the generated markdown archive that ships with @olilarkin/cdp-wasm
// (docs/effects/*.md, docs/generators.md, docs/guide/*.md, plus the index
// READMEs). Those pages are themselves generated from the catalog + CDP
// reference, so this manual can never drift from the effects the app exposes.
//
// We pre-render markdown → HTML here (Node), not in the browser: the doc set is
// a controlled, generated subset of markdown, so a compact converter covers it
// and the app ships no markdown parser. Internal links (`effects/blur.md#anchor`,
// `#anchor`, `../README.md`) are resolved at build time to data-page/data-anchor
// attributes, so the viewer only has to read those — no path juggling at runtime.
//
// manual.json is a committed, derived artifact (like ./vendor): re-run
// `npm run docs:manual` and commit it whenever the cdp-wasm docs change. The site
// build copies repo-root files into dist/, so no extra wiring is needed to ship it.

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { RECIPES } from '../src/data/recipes.js';
import { EFFECTS } from '@olilarkin/cdp-wasm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Prefer the linked source package (freshest); fall back to the vendored snapshot.
const DOCS = [
  join(root, 'node_modules/@olilarkin/cdp-wasm/docs'),
  join(root, 'vendor/@olilarkin/cdp-wasm/docs'),
].find((p) => existsSync(p));

if (!DOCS) {
  console.error('✗ cdp-wasm docs not found. Run `npm install` (with ../cdp-wasm present) first.');
  process.exit(1);
}

// ---- collect the curated markdown (everything except the tools/ pipeline) -----
function walk(dir, rel = '') {
  const out = [];
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name);
    const r = rel ? posix.join(rel, name) : name;
    if (statSync(abs).isDirectory()) {
      if (name === 'tools') continue; // harvest intermediates + build scripts — not for readers
      out.push(...walk(abs, r));
    } else if (name.endsWith('.md')) {
      out.push(r);
    }
  }
  return out;
}

// Repo-local, user-authored overlay. Pages here override the cdp-wasm base by
// slug (e.g. a friendly Overview replaces the package's dev README) and add
// app-only topics the engine docs don't cover (e.g. the Faust nodes).
const LOCAL = join(root, 'manual');

// Strip generator/package boilerplate from the cdp-wasm base pages so the manual
// reads for musicians, not maintainers: the "do not edit" stamp on every page,
// the per-effect ".htm / exposed cdp-wasm surface" note, and the generators
// intro's package internals. Best-effort — if upstream rewording stops a pattern
// matching, the page still builds, just with the original line.
function clean(md) {
  md = md
    // dev "do not edit" stamp on every generated page
    .replace(/\n+(?:---\n+)?_Generated by[^\n]*_\s*$/i, '')
    // per-effect ".htm / exposed cdp-wasm surface" note
    .replace(/^Reference distilled from CDP[^\n]*\n\n?/im, '')
    // generators intro package internals → plain, app-facing wording
    .replace(/ \(`GENERATORS` in the package, run by `applyGenerator`\)/, '')
    .replace(/ The output sample rate follows `applyGenerator`[’'`]s `extra\.sampleRate`[\s\S]*?token in each arg template\./,
      ' They render at the session sample rate (set in Options ▸ Sample rate).');

  // Conceptual guides carry developer material (npm package API) alongside the
  // concepts. Keep the concepts, drop the dev bits: remove the pure-API section
  // (redundant with the in-app one), reframe the "what the library does" heading,
  // strip package code examples + dev-file links, and trim known dev asides.
  md = md.split(/(?=^## )/m)
    .filter((s) => !/^## Using an envelope from the package/i.test(s))
    .join('');
  md = md
    .replace(/^## What cdp-wasm does for you/im, '## What happens automatically')
    // package code examples
    .replace(/```[a-z]*\n[\s\S]*?```\n?/g, (b) =>
      /@olilarkin\/cdp-wasm|applyEffect|applyGenerator|cdp\.|EFFECTS\.find/.test(b) ? '' : b)
    // dev-file links → plain text, then remove the now-bare dev parentheticals
    .replace(/\[([^\]]+)\]\((?:\.\.\/)*npm\/[^)]*\)/g, '$1')
    .replace(/\s*\(see `npm\/[^`]*`\)/g, '')
    .replace(/\s*\(auto-generated by `[^`]*`\)/g, '')
    .replace(/\s*\(`applyGenerator`[’'`]s `extra\.data`\)/g, '')
    // implementation asides (whole sentences), removed once their links are gone
    .replace(/\s*The set is\s+probed per effect into[\s\S]*?probe-breakpoints\.mjs`\)\./, '')
    .replace(/,?\s*but if you are building long spectral chains by hand[\s\S]*?wrapping is done\./, '.')
    .replace(/\s*The\s+primitive\s+behind\s+this\s+is\s+`cdp\.[^`]*`\s*\./, '')
    // reframe library-API actors for app users (whitespace-flexible: the source
    // prose wraps mid-sentence, so match \s+ between words rather than literal spaces)
    .replace(/When\s+you\s+call\s+`applyEffect\(\)`\s+\(or\s+load\s+the\s+effect\s+in\s+a\s+consuming\s+app\)\s+the\s+package\s+runs/g, 'The app runs')
    .replace(/Every\s+catalog\s+effect\s+marked\s+`domain: 'spectral'`\s+is/g, 'Every spectral effect is')
    .replace(/`applyEffect\(\)`/g, 'the app')
    .replace(/`applyGenerator\(\)`/g, 'the app')
    .replace(/`mono: true` effect/g, 'mono-only effect')
    .replace(/the\s+package\s+conforms\s+the\s+second\s+source[’']s[\s\S]*?need\s+them\s+directly\./,
      "the app conforms the second source’s sample rate and channel count to the first, so the two sounds are compatible.");
  return md;
}

// ---- markdown → HTML (the subset these generated docs actually use) ----------
const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Resolve a link target found in `fileRel` to { external | page | anchor }.
function resolveTarget(fileRel, target) {
  if (/^https?:/i.test(target)) return { external: true, url: target };
  if (target.startsWith('#')) return { anchor: target.slice(1) }; // same-page anchor
  const [pathPart, anchor] = target.split('#');
  let abs = posix.normalize(posix.join(posix.dirname(fileRel), pathPart));
  if (abs.endsWith('/')) abs += 'README'; // directory link → its index page
  return { page: abs.replace(/\.md$/, ''), anchor: anchor || null };
}

// Inline spans. Code spans are pulled out to a side list and replaced with a
// sentinel (U+FFFC — can't occur in the docs and carries no markdown-significant
// characters), so the link/bold/italic passes run over the whole line — bold that
// wraps a code span (`**\`yes\`**`) still works — then the code is restored last.
// Everything outside code is trusted generated prose, left as-is so its literal
// HTML entities survive.
const SENTINEL = String.fromCharCode(0xFFFC); // U+FFFC
function inline(text, fileRel) {
  const codes = [];
  text = text.replace(/`([^`]+)`/g, (_, c) => {
    codes.push('<code>' + escapeHtml(c) + '</code>');
    return SENTINEL + (codes.length - 1) + SENTINEL;
  });
  text = text
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label, target) => {
      const r = resolveTarget(fileRel, target.trim());
      if (r.external) return `<a href="${r.url}" target="_blank" rel="noopener">${label}</a>`;
      const attrs = ['href="#"'];
      if (r.page) attrs.push(`data-page="${r.page}"`);
      if (r.anchor) attrs.push(`data-anchor="${r.anchor}"`);
      return `<a ${attrs.join(' ')}>${label}</a>`;
    })
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    // underscore italics, only when the underscores sit on word boundaries (so
    // identifiers like convert_to_midi are left alone)
    .replace(/(^|[^\w])_([^_]+)_(?=$|[^\w])/g, '$1<em>$2</em>');
  return text.replace(new RegExp(SENTINEL + '(\\d+)' + SENTINEL, 'g'), (_, n) => codes[+n]);
}

function renderTable(rows, fileRel) {
  const cells = (r) => r.trim().replace(/^\|/, '').replace(/\|\s*$/, '').split('|').map((c) => c.trim());
  const head = cells(rows[0]).map((c) => `<th>${inline(c, fileRel)}</th>`).join('');
  const body = rows.slice(2).map((r) => '<tr>' + cells(r).map((c) => `<td>${inline(c, fileRel)}</td>`).join('') + '</tr>').join('');
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}

function convert(md, fileRel) {
  const lines = md.replace(/\r\n/g, '\n').split('\n');
  const out = [];
  let para = [];
  const flush = () => { if (para.length) { out.push('<p>' + inline(para.join(' '), fileRel) + '</p>'); para = []; } };
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.startsWith('```')) {
      flush(); i++;
      const code = [];
      while (i < lines.length && !lines[i].startsWith('```')) { code.push(lines[i]); i++; }
      i++; // closing fence
      out.push('<pre><code>' + escapeHtml(code.join('\n')) + '</code></pre>');
    } else if (line.trimStart().startsWith('|')) {
      flush();
      const rows = [];
      while (i < lines.length && lines[i].trimStart().startsWith('|')) { rows.push(lines[i]); i++; }
      out.push(renderTable(rows, fileRel));
    } else if (/^(#{1,6})\s+(.*)$/.test(line)) {
      flush();
      const [, hashes, rest] = /^(#{1,6})\s+(.*)$/.exec(line);
      out.push(`<h${hashes.length}>${inline(rest, fileRel)}</h${hashes.length}>`);
      i++;
    } else if (/^---+\s*$/.test(line)) {
      flush(); out.push('<hr>'); i++;
    } else if (/^<a\b/.test(line.trim())) {
      flush(); out.push(line.trim()); i++; // pass through <a id="…"></a> anchors
    } else if (line.startsWith('>')) {
      flush();
      const bq = [];
      while (i < lines.length && lines[i].startsWith('>')) { bq.push(lines[i].replace(/^>\s?/, '')); i++; }
      out.push('<blockquote>' + inline(bq.join(' '), fileRel) + '</blockquote>');
    } else if (/^-\s+/.test(line)) {
      flush();
      const items = [];
      while (i < lines.length && /^-\s+/.test(lines[i])) { items.push(lines[i].replace(/^-\s+/, '')); i++; }
      out.push('<ul>' + items.map((it) => '<li>' + inline(it, fileRel) + '</li>').join('') + '</ul>');
    } else if (line.trim() === '') {
      flush(); i++;
    } else {
      para.push(line.trim()); i++;
    }
  }
  flush();
  return out.join('\n');
}

// Plain-text H1, for nav labels and the page heading.
function h1Title(md) {
  const m = /^#\s+(.*)$/m.exec(md);
  if (!m) return '';
  return m[1].replace(/`/g, '').replace(/\*\*/g, '').replace(/\[([^\]]+)\]\([^)]+\)/g, '$1').trim();
}

// ---- Recipes page (generated from recipes.js, kept in sync with the app) ------
// The 36 File ▸ Recipes patches, grouped by category, each with a readable signal
// flow and links to the effects it uses. Generated (not authored) so it can't drift
// from recipes.js. Effect links are flat (effects/<program>#<id>) so they resolve
// in the manual's slug space.
const byProgram = Object.fromEntries(EFFECTS.map((e) => [e.id, e]));
const GEN_LABEL = { wave: 'Waveform', noise: 'White noise', impulse: 'Impulse train', multiosc: 'Nested osc', chord: 'Chord', clicks: 'Clicks', synspline: 'Spline synth', chirikov: 'Chirikov' };
function recipeFlow(r) {
  const node = (id) => r.nodes.find((n) => n.id === id);
  const back = (id) => r.edges.find((e) => e.to.node === id && e.to.port === 'in');
  const chain = [];
  let cur = r.nodes.find((n) => n.type === 'output');
  while (cur) { chain.unshift(cur); const e = back(cur.id); cur = e ? node(e.from.node) : null; }
  const label = (n) =>
    n.type === 'generator' ? (GEN_LABEL[n.gen.id] || n.gen.id)
      : n.type === 'transform' ? `\`${n.effectId}\``
      : n.type === 'pvocAnalyse' ? 'pvoc anal'
      : n.type === 'pvocResynth' ? 'pvoc synth'
      : n.type === 'output' ? 'Output'
      : n.type === 'source' ? (n.source?.name ? `${n.source.name}.wav` : 'Source (file)')
      : n.type === 'faust' ? `Faust ${n.faust?.kind || ''}`.trim()
      : n.type;
  const two = r.edges.some((e) => e.to.port === 'in2');
  return chain.map(label).join(' → ') + (two ? '  _(+ 2nd source)_' : '');
}
function recipesMarkdown() {
  const md = ['# Recipes', '',
    `${RECIPES.length} ready-made patches, loadable from **File ▸ Recipes**. Each is `
    + `self-contained — a synth generator (or a bundled sound) feeds the chain — so `
    + `pressing **▶** on the Output renders audio right away. Open one to hear it, then `
    + `tweak any node, or swap in your own sound with **File ▸ Add source**.`, ''];
  let cat = null;
  for (const r of RECIPES) {
    const c = r.metadata?.category || 'Other';
    if (c !== cat) { md.push(`## ${c}`, ''); cat = c; }
    const uses = [...new Set(r.nodes.filter((n) => n.type === 'transform').map((n) => n.effectId))];
    const links = uses.map((id) => `[\`${id}\`](effects/${byProgram[id]?.program}.md#${id})`).join(', ') || '—';
    md.push(`### ${r.metadata?.name || 'Recipe'}`, '', r.metadata?.description || '', '',
      `**Signal flow:** ${recipeFlow(r)}`, '', `**Uses:** ${links}`, '');
  }
  return md.join('\n');
}

// ---- render every page -------------------------------------------------------
// Base (cdp-wasm, cleaned) first, then the repo-local overlay so its pages win.
const sources = [
  ...walk(DOCS).map((rel) => ({ rel, dir: DOCS, base: true })),
  ...(existsSync(LOCAL) ? walk(LOCAL).map((rel) => ({ rel, dir: LOCAL, base: false })) : []),
];

const pages = {};
let overrides = 0;
for (const { rel, dir, base } of sources) {
  const slug = rel.replace(/\.md$/, '');
  if (!base && pages[slug]) overrides++;
  let md = readFileSync(join(dir, rel), 'utf8');
  if (base) md = clean(md);
  pages[slug] = { title: h1Title(md) || slug, html: convert(md, rel) };
}

// Generated Recipes page (data-driven, so it lives here rather than in manual/).
pages.recipes = { title: 'Recipes', html: convert(recipesMarkdown(), 'recipes.md') };

// ---- nav sidebar -------------------------------------------------------------
const has = (slug) => Object.prototype.hasOwnProperty.call(pages, slug);
const entry = (slug, label) => ({ slug, label: label || pages[slug].title });

const GUIDE_ORDER = ['guide/README', 'guide/spectral-pvoc', 'guide/breakpoints', 'guide/mono-and-channels'];
const guideSlugs = Object.keys(pages).filter((s) => s.startsWith('guide/'));
guideSlugs.sort((a, b) => {
  const ia = GUIDE_ORDER.indexOf(a), ib = GUIDE_ORDER.indexOf(b);
  return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
});

const effectSlugs = Object.keys(pages)
  .filter((s) => s.startsWith('effects/') && s !== 'effects/README')
  .sort();

const nav = [];
if (has('README')) nav.push({ title: null, pages: [entry('README', 'Overview')] });
if (has('interface')) nav.push({ title: null, pages: [entry('interface', 'The patcher window')] });
if (guideSlugs.length) nav.push({ title: 'Guide', pages: guideSlugs.map((s) => entry(s)) });
if (has('recipes')) nav.push({ title: 'Recipes', pages: [entry('recipes', 'Recipes')] });
if (has('generators')) nav.push({ title: 'Generators', pages: [entry('generators', 'Generators')] });
if (has('faust')) nav.push({ title: 'Faust', pages: [entry('faust')] });
const hostPages = [];
if (has('extension')) hostPages.push(entry('extension', 'Extension'));
if (has('plugin')) hostPages.push(entry('plugin', 'Plugin'));
if (hostPages.length) nav.push({ title: 'In a DAW', pages: hostPages });
if (effectSlugs.length) {
  const effectPages = [];
  if (has('effects/README')) effectPages.push(entry('effects/README', 'All effects'));
  effectPages.push(...effectSlugs.map((s) => entry(s)));
  nav.push({ title: 'Effects', pages: effectPages });
}

const manual = {
  generated: 'run `npm run docs:manual` to regenerate — do not edit by hand',
  home: has('README') ? 'README' : Object.keys(pages)[0],
  nav,
  pages,
};

writeFileSync(join(root, 'manual.json'), JSON.stringify(manual));
console.log(`✓ manual.json — ${Object.keys(pages).length} pages`
  + `${existsSync(LOCAL) ? ` (+${overrides} local override(s) from manual/)` : ''}`);
