// render-recipes.mjs — generate recipes/README.md from src/data/recipes.js so the
// catalogue stays in sync with the actual recipes. recipes.js only imports the
// catalog (no DOM), so it loads headlessly.
//   npm run docs:recipes   (node scripts/render-recipes.mjs)

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { RECIPES } from '../src/data/recipes.js';
import { EFFECTS } from '@olilarkin/cdp-wasm';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUTDIR = resolve(HERE, '../recipes');
const byId = Object.fromEntries(EFFECTS.map((e) => [e.id, e]));
const genLabel = { wave: 'Waveform', noise: 'White noise', impulse: 'Impulse train', multiosc: 'Nested osc', chord: 'Chord', clicks: 'Clicks', synspline: 'Spline synth', chirikov: 'Chirikov' };

// Describe a recipe's signal flow as a readable chain from its nodes/edges.
function flow(recipe) {
  const node = (id) => recipe.nodes.find((n) => n.id === id);
  const out = recipe.nodes.find((n) => n.type === 'output');
  // follow edges backwards from output to build the main path
  const back = (id) => recipe.edges.find((e) => e.to.node === id && e.to.port === 'in');
  const chain = [];
  let cur = out;
  while (cur) {
    chain.unshift(cur);
    const e = back(cur.id);
    cur = e ? node(e.from.node) : null;
  }
  const label = (n) => {
    if (n.type === 'generator') return genLabel[n.gen.id] || n.gen.id;
    if (n.type === 'transform') return `\`${n.effectId}\``;
    if (n.type === 'pvocAnalyse') return 'pvoc anal';
    if (n.type === 'pvocResynth') return 'pvoc synth';
    if (n.type === 'output') return 'Output';
    if (n.type === 'source') return n.source?.name ? `${n.source.name}.wav` : 'Source (file)';
    if (n.type === 'faust') return `Faust ${n.faust?.kind || ''}`.trim();
    return n.type;
  };
  const parts = chain.map(label);
  // note a second input if any transform has an in2 edge
  const two = recipe.edges.some((e) => e.to.port === 'in2');
  return parts.join(' → ') + (two ? '  _(+ 2nd source)_' : '');
}

const effectsUsed = (recipe) => [...new Set(recipe.nodes.filter((n) => n.type === 'transform').map((n) => n.effectId))];

mkdirSync(OUTDIR, { recursive: true });
const md = ['# Demo recipes', '',
  `${RECIPES.length} ready-made patches. In the [demo](../../demo/), open **File ▸ Recipes** and pick one — each is self-contained (a synth generator feeds the chain), so pressing **▶** on the Output renders audio immediately. Tweak any node, or swap the generator for **File ▸ Add source** to run a recipe on your own sound.`,
  '', 'Every recipe here is verified by `npm run test:recipes` (each is rendered through the demo\'s graph runner and checked for audio output).', ''];

let cat = null;
for (const r of RECIPES) {
  const c = r.metadata?.category || 'Other';
  if (c !== cat) { md.push(`## ${c}`, ''); cat = c; }
  md.push(`### ${r.metadata?.name || 'Recipe'}`, '', r.metadata?.description || '', '',
    `**Signal flow:** ${flow(r)}`, '',
    `**Effects:** ${effectsUsed(r).map((id) => `[\`${id}\`](../effects/${byId[id]?.program}.md#${id})`).join(', ') || '—'}`, '');
}
md.push('---', '', 'Recipes live in [`src/data/recipes.js`](../src/data/recipes.js); this page is generated by `scripts/render-recipes.mjs`.');
writeFileSync(resolve(OUTDIR, 'README.md'), md.join('\n') + '\n');
console.log(`rendered recipe catalogue for ${RECIPES.length} recipes -> recipes/README.md`);
